### ISSUE TITLE
Got no token / no script

### ISSUE THREAD

**Issue by wilderkaiser** [jandeilson/TalkToUsOnWhatsApp-PHP#1]
Hello, writing to DB is working but there is no token in DB -> so?? ... no script is displayed after pressing "generate" Button on generator.html

**Comment by wilderkaiser** [comment]
update: have added "processDashboard.php" with code from "processGenerator.php"  ... token is written in DB now !

**Comment by jandeilson** [comment]
Yes, this is one of the problems. I am already correcting... I have also identified that it is necessary to assign the appropriate directory permissions. Thank you! :)

**Comment by jandeilson** [comment]
I just sent the correction. :)

**Comment by wilderkaiser** [comment]
Dont worry .. Great work! Directory perms are ok here ... just a little bit tricky to set the right path(s) Integrating sendgrid is a little bit confusing me ..
